spring:
  datasource:
    password:Yzf270701#
    name:root
    driver-class-name:com.mysql.jdbc.Driver
    url:jdbc\:mysql\://172.23.40.211\:3306/yzf_biz?useUnicode\=true&allowMultiQueries\=true&characterEncoding\=utf-8&zeroDateTimeBehavior\=convertToNull
spring1:
     password:Yzf270701#